


######################### theme kunka condigure ##############################################
# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "/blog" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: Jekyll Theme
description: Just another Jekyll theme design and code by zhanxin.info.
keywords: Jekyll Theme
url: /blog
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: index.html
  - text: 分类目录 
    url: navigations/categories.html
  - text: 文章归档
    url: navigations/archives.html
  - text: 联系我
    url: navigations/contact.html
  - text: 友情链接
    url: navigations/links.html

#Author config
author:
    name: holly
    email: 
    imageLink: http://image.baidu.com/search/detail?ct=503316480&z=0&ipn=d&word=%E5%A4%B4%E5%83%8F%20%E5%8D%A1%E9%80%9A%E5%8A%A8%E6%BC%AB%20%E6%BC%AB%E7%94%BB&pn=32&spn=0&di=158614709880&pi=&rn=1&tn=baiduimagedetail&istype=&ie=utf-8&oe=utf-8&in=3354&cl=2&st=&cs=3755214395%2C2447681018&os=3466223155%2C2159601931&simid=3462756739%2C429808984&adpicid=0&ln=1000&fr=ala&fmq=1378374347070_R&s=0&se=&sme=&tab=&face=&ist=&jit=&statnum=head&cg=&bdtype=0&objurl=http%3A%2F%2Fimg4.qzone.cc%2Fomm%2F3838%2F845252.jpg&fromurl=ippr_z2C%24qAzdH3FAzdH3Fooo_z%26e3Bqz5gj_z%26e3BvvAzdH3Fqqp57xtwg2AzdH3Fhwp5g2AzdH3Fmmn88_z%26e3Bip4s&gsm=3c
    simpleIntro: 每天都否定错误的想法，正确的肯定会来的
    detailIntro:
      <p>hello</p>
#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com
  - class: icon-renren
    url: http://renren.com
  - class: icon-github-alt
    url: http://github.com
  - class: icon-twitter
    url: http://twitter.com
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: 掌心
      url: http://www.zhanxin.info
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://www.zhanxin.info/themes.html
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#comment config
disqus:
  config: true
  id: holly


#################################### global configure #######################################

username: holly-juan
baseurl: /blog
markdown: redcarpet
safe: false
highlighter: pygments
title: holly的博客
description: 每天都否定错误的想法，正确的肯定会来的
theme: kunka
disqusname: holly

# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine, kunka
# those themes are all come from GitHub Pages Themes
